"📚 docs":
  - changed-files:
  - any-glob-to-any-file:
      - "docs/**"
      - "packages/*/README.md"
      - "README.md"
"🧪 tests":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/*/tests/*.ts"
"📦 animeflv":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/animeflv/**"
"📦 jkanime":
  - changed-files:
      - any-glob-to-any-file:
  - "packages/jkanime/**"
"⚙️ configs":
  - changed-files:
      - any-glob-to-any-file:
          - ".prettierrc"
          - "vitest.config.ts"
          - "eslint.config.js"
